export * from './types'
export * from './styles'
export { Header } from './header'
export { MainLayout } from './layout'
export { MainPage } from './main-page'
export { Footer } from './footer'
export { MainScreen } from './main-screen'
export { SliderCandles } from './slider-candles'
export { Candles } from './candles'
export { Transform } from './transform'
export { Reviews } from './reviews'
export { Amulet } from './amulet'
export { Testimonials } from './testimonials'
export { Menu } from './menu'
export { Faq } from './faq'
export { MyModal } from './modal'
export { ThanksModal } from './thanks-modal'
